#!/bin/bash

# Script to install Fedy <http://satya164.github.io/fedy/>.
# Copyright (C) 2014  Satyajit sahoo

if [[ ! $(whoami) = "root" ]]; then
    echo "Please run the script as root."
    exit 1
fi


echo "Adding repositories..."

if [[ ! -f /etc/yum.repos.d/ozonos.repo ]]; then
cat <<EOF | tee /etc/yum.repos.d/ozonos.repo > /dev/null 2>&1
[ozonos]
name=Repository for Ozon OS
baseurl=http://goodies.ozon-os.com/repo/\$releasever/
enabled=1
skip_if_unavailable=1
metadata_expire=1d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ozonos
EOF
fi

rpm --quiet --query rpmfusion-free-release || dnf -y --nogpgcheck install http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
rpm --quiet --query rpmfusion-nonfree-release || dnf -y --nogpgcheck install http://download1.rpmfusion.org/free/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm


echo "Installing fedy..."

dnf -y --nogpgcheck install fedy

# Please report bugs at <http://github.com/satya164/fedy/issues>
# End of the Script
