#!/bin/bash
# Script to install Fez <http://satya164.github.io/fez/>.
# Copyright (C) 2012  Satyajit sahoo

if [[ ! $(whoami) = "root" ]]; then
    echo "Please run the script as root."
    exit 1
fi

# Add the repo
echo "Adding repository..."
cat <<EOF | tee /etc/yum.repos.d/fez.repo > /dev/null 2>&1
[fez]
name=Fez
type=rpm-md
baseurl=http://download.opensuse.org/repositories/home:/satya164:/fez/Fedora_\$releasever/
gpgkey=http://download.opensuse.org/repositories/home:/satya164:/fez/Fedora_\$releasever/repodata/repomd.xml.key
gpgcheck=1
enabled=1
metadata_expire=1d
skip_if_unavailable=1
EOF

# Install dependencies
echo "Installing dependencies..."
yum -y install --nogpgcheck --skip-broken coreutils curl sed tar unzip wget yad


# Test if the repo is available for current Fedora version and install the package
echo "Installing fez..."
fver="$(rpm -E %fedora)"
curl -s -f -L "http://download.opensuse.org/repositories/home:/satya164:/fez/Fedora_${fver}/repodata/repomd.xml" -o /dev/null
if [[ $? -eq 0 ]]; then
    yum -y install --nogpgcheck --skip-broken fez
else
    yum -y install --nogpgcheck --skip-broken --releasever="$((fver-1))" fez
fi

# Please report bugs at <http://github.com/satya164/fez/issues>
# End of the Script
